<?php require 'GZIP.php'; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>GZIP HTML with PHP</title>
<link rel="stylesheet" media="screen" href="Assets/Styles/Styles.php" />
</head>
<body>

   <p style="color:red; font-weight:bold;">Above HTML GZIP code will check whether your browser supports gzip, if yes, then it send ob_gzhandler method as handle to ob_start method which buffers the output. Thus output is compressed using ob_gzhandler. Only problem with this method is that you have to manually edit all PHP files or should have a header.php file that gets included in all files.</p>   
   
   Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eu dui magna. Mauris lacinia consectetur semper. Maecenas vitae rhoncus magna. Donec non neque sit amet neque commodo auctor non nec nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec laoreet, urna nec hendrerit lacinia, lacus enim congue magna, eget lobortis neque felis eget odio. Sed non augue ante, quis ornare lorem. Donec eget metus tortor. Sed eleifend, est id pretium aliquam, nisl sapien hendrerit turpis, quis ultrices nulla felis at elit. Duis ultrices, dui ac rutrum iaculis, turpis elit elementum tellus, a porttitor justo orci non massa.

Nunc eu aliquam metus. Mauris sodales consectetur orci vitae imperdiet. Quisque tristique convallis tortor, eget gravida ligula tincidunt vel. Aliquam luctus, nulla non cursus auctor, ipsum mi eleifend quam, at cursus mauris felis sed justo. Nam et ornare magna. Donec vel ante a tellus pharetra congue vel nec turpis. Sed id erat enim. Sed erat enim, luctus non auctor vitae, lacinia luctus turpis. Proin auctor lorem vel sapien tincidunt egestas. Proin ligula diam, tincidunt eu vehicula at, pretium vitae ante. Proin sem nulla, eleifend at mollis et, condimentum at justo. Aliquam vitae felis lorem. Etiam vitae eleifend nisl. In at metus ut odio iaculis ullamcorper.

Quisque aliquet nulla nec velit rhoncus sed vestibulum odio porttitor. Mauris et lectus nec massa tincidunt placerat. Quisque nec mauris tortor, accumsan suscipit leo. Etiam adipiscing luctus justo quis dictum. Proin viverra consequat orci a ultrices. Vivamus egestas varius lectus quis fermentum. Sed et ante nec lacus suscipit lobortis condimentum in nulla. Vestibulum sit amet velit lacus. Etiam iaculis ultrices hendrerit. Cras non vulputate neque. Nam lacinia convallis nulla ut feugiat. Duis sed ligula orci, ac euismod massa. Vestibulum leo purus, ullamcorper vitae vestibulum et, vehicula a mauris. Fusce commodo interdum lacinia. Sed ac lectus dolor, sit amet feugiat ante. Maecenas velit sem, vestibulum eu venenatis non, volutpat et odio. Donec venenatis pretium bibendum.

Vestibulum feugiat odio nulla. Donec ut eros quis ipsum tincidunt suscipit. Nam et tortor id metus placerat pulvinar. Praesent auctor sollicitudin tortor eu aliquet. Maecenas quis nisi lacus. Vivamus nunc lorem, euismod sit amet fermentum in, rutrum et leo. Vestibulum ultrices odio eget sem pulvinar elementum. Aenean quis mi dui. Sed tincidunt tellus vestibulum arcu pulvinar a mollis urna auctor. In quis purus lorem. Morbi eleifend scelerisque diam eu sollicitudin. Mauris lorem magna, dapibus sed mollis venenatis, tempor vel urna. Nullam lobortis posuere pharetra.

Aliquam sagittis odio at lorem eleifend eget feugiat nunc elementum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse vel sollicitudin neque. Vestibulum pretium, lectus eu feugiat aliquam, elit magna aliquam ipsum, imperdiet porta ligula ante eu urna. Vestibulum sit amet nisl at mi vehicula eleifend. Sed magna sem, condimentum a mattis quis, ornare id quam. Nulla facilisi. Integer ut volutpat libero. Morbi arcu dolor, elementum non commodo vitae, sollicitudin at neque. Fusce eu urna lorem. Fusce leo massa, interdum eu lacinia id, consequat viverra elit.

Ut adipiscing dictum dolor. Suspendisse pellentesque volutpat nisi, at fringilla leo ultrices id. Integer massa mi, aliquam id auctor quis, auctor a est. Maecenas nulla metus, scelerisque in semper eget, ultrices ut velit. Nulla facilisis lacus nec felis congue eget viverra mi scelerisque. Nam vulputate velit mi. Mauris libero arcu, egestas ut congue sed, ultricies ut velit. Aenean commodo placerat condimentum. Vivamus eget massa lectus. Etiam elementum tortor sit amet orci semper aliquam. Curabitur pretium dapibus quam, et blandit nulla tincidunt ut. Ut urna magna, gravida ut fermentum vitae, egestas id diam. Duis id condimentum sapien. Vestibulum at neque mi. Integer sed turpis magna. Etiam a odio dui.

Morbi sit amet justo ac ipsum porttitor gravida. Donec eget mauris ligula, facilisis commodo nibh. Maecenas porta, tellus non pulvinar congue, ipsum nisl lobortis odio, vitae luctus augue neque eget leo. Donec nulla mauris, molestie ut ullamcorper quis, laoreet vel lacus. Donec cursus convallis est, id condimentum leo ullamcorper ut. Morbi in ante ut massa fermentum suscipit eu a libero. Quisque erat lectus, mattis id venenatis sagittis, sagittis vitae turpis. In hac habitasse platea dictumst. Integer libero leo, fermentum quis mollis ac, luctus sit amet dui. Aenean sodales egestas leo eget cursus.

Proin consequat euismod iaculis. Nunc rutrum, urna sed mollis pulvinar, libero orci sodales nulla, id porttitor lacus nisl quis neque. Donec vel lectus ac purus porta ornare. Proin fringilla viverra consectetur. Aliquam nulla nulla, fringilla eget gravida vel, rhoncus rhoncus nulla. Nam sed diam vel lorem fermentum dignissim in eu dui. Pellentesque sit amet ipsum nec risus tempor imperdiet et in tortor. Vestibulum risus odio, iaculis accumsan suscipit in, ornare ut diam. Morbi vel quam et mauris venenatis dignissim sit amet non lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc enim lorem, aliquet id convallis ac, rhoncus sed purus.

Proin placerat rutrum lacus, at bibendum dolor luctus ut. Vivamus rhoncus molestie mauris ac dapibus. Curabitur vel tellus ac leo feugiat condimentum ac sit amet erat. Nullam ut sapien tellus, in venenatis turpis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras eget sem non magna cursus faucibus. Proin pellentesque placerat convallis. Cras dignissim vehicula lacinia. In hac habitasse platea dictumst. Pellentesque tempus auctor fermentum. Etiam blandit vehicula eleifend.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam a ullamcorper velit. Sed cursus diam non velit lobortis accumsan sollicitudin orci dictum. In hac habitasse platea dictumst. Curabitur tincidunt nisi ac velit pharetra eget consectetur quam tristique. Praesent in ultrices elit. Etiam a dolor ut orci facilisis eleifend at sit amet ipsum. Donec in urna tortor. In convallis mollis urna, quis venenatis ante rutrum nec. Etiam consectetur dui nec diam viverra vel dapibus ante dapibus.

Ut nec erat eu dui scelerisque porttitor sit amet sit amet orci. Phasellus nisi felis, vehicula non mattis a, fringilla id libero. Mauris eget tellus nulla, et commodo libero. Integer auctor nunc sed ipsum pellentesque mattis. Aliquam erat volutpat. Phasellus ut urna eu purus accumsan sodales a vitae sapien. Vivamus auctor, nulla a ornare lacinia, leo ipsum gravida lacus, in mollis ante neque varius est. Suspendisse odio odio, ultricies a interdum ac, dignissim ac enim. Morbi tempor condimentum nisl, eget convallis libero pellentesque id. Vestibulum a enim et nisi imperdiet posuere eget ac dui. Morbi a accumsan massa. Nullam eget augue id ligula lacinia facilisis. Integer commodo augue enim, non dictum enim. Fusce vel lacus sit amet mi adipiscing tempus. Etiam rhoncus quam et neque tincidunt pulvinar. Nunc quis lectus erat, at ultrices lacus. Fusce sit amet lorem erat, at faucibus mi. Mauris ac risus sed dui pretium varius ac non sapien. Nulla est nulla, lobortis eget scelerisque ac, volutpat sed risus.

In bibendum condimentum sollicitudin. Donec scelerisque, risus sit amet egestas pretium, nisi urna egestas nulla, eu rhoncus ipsum metus sed purus. Quisque libero nisl, volutpat vel molestie a, tempus auctor mauris. Donec enim eros, cursus vitae suscipit nec, venenatis ut sapien. Vestibulum vestibulum dignissim quam a commodo. Curabitur id arcu at arcu pellentesque tincidunt. Cras vel velit sapien. Sed leo sapien, pretium sit amet luctus sit amet, eleifend sed diam. Donec vestibulum, nisi vel commodo ullamcorper, mi libero ullamcorper nisi, in fermentum quam risus vitae erat. Duis ut risus mauris. Nam malesuada magna ut augue euismod varius. Aliquam erat volutpat. Sed porttitor quam sed magna sollicitudin venenatis.

Quisque nisi neque, sagittis at laoreet non, interdum quis nulla. Aliquam sollicitudin ultrices metus nec consequat. Nunc adipiscing, arcu ut rutrum hendrerit, quam ipsum auctor magna, vel sagittis nisl turpis id ipsum. Etiam faucibus, est non venenatis vestibulum, tellus sapien feugiat risus, a posuere nisi nisl nec elit. Aenean quis magna erat. Vivamus fringilla nisi a risus sollicitudin eget molestie eros tempus. Praesent interdum dui vel eros hendrerit fermentum. Aliquam at nulla a sapien facilisis gravida sit amet id mi. Nam posuere ornare sapien ac pharetra. Aenean aliquet vestibulum metus, et iaculis velit laoreet non.

Proin a mi ante, eget hendrerit nunc. Nullam eleifend urna ut magna porttitor a mattis nisl convallis. Nunc varius ipsum a risus dictum eget fermentum magna posuere. Phasellus sagittis cursus arcu, eget tincidunt felis lobortis et. Nunc semper lectus non arcu dictum eget vulputate justo tristique. Vestibulum auctor commodo sem sit amet tempus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam metus tortor, laoreet non lobortis sit amet, fermentum id dui. Duis mi est, aliquet sed luctus imperdiet, rutrum eget arcu. Etiam eleifend ullamcorper eros nec vehicula.

Duis id urna et nibh commodo facilisis fringilla eget ante. Integer nec ligula purus. Suspendisse porttitor, velit id tempus porta, orci augue dictum quam, sit amet accumsan sapien sapien id nibh. Duis eget enim in tellus consectetur malesuada nec a felis. Vestibulum eget velit eu mauris semper porta. In quis leo eros, nec egestas felis. Quisque a sapien mi, consectetur dapibus neque. Mauris at mattis quam. Donec a metus eros. Fusce cursus ipsum ut lacus consectetur id posuere mi cursus. Vestibulum sapien lorem, eleifend eget facilisis vel, dictum ac purus. Etiam commodo nibh vel augue aliquet in commodo diam vehicula. Nam a tristique leo. Pellentesque ullamcorper, quam a aliquam egestas, quam arcu rhoncus augue, vel accumsan ligula purus eget sem. Curabitur cursus dignissim tortor, ac luctus lacus fringilla gravida. Suspendisse lobortis pellentesque elit, a iaculis tortor sodales adipiscing. Aenean venenatis pharetra dolor, at porttitor velit tincidunt id. Vivamus et nulla velit, vel eleifend enim. Nulla non lectus vitae justo vehicula porttitor.

Sed tempus tempus odio et porttitor. Quisque vel aliquam urna. Aliquam erat volutpat. Nullam varius neque non dolor auctor non pretium nisi rhoncus. Mauris sollicitudin accumsan nisl a hendrerit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam justo dolor, sollicitudin vitae porta vel, placerat ut turpis. Maecenas elementum dignissim nisi, sed adipiscing justo gravida vitae. Donec luctus, sem sed porta dictum, metus nulla eleifend eros, vel semper metus felis in metus. Nulla fringilla libero in est iaculis pharetra interdum enim euismod. Pellentesque consectetur condimentum quam gravida sollicitudin. Vestibulum et metus nibh, vitae consectetur erat. Etiam ut accumsan sem.

Integer interdum gravida neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam elit urna, blandit eu dictum eu, consequat non diam. Integer condimentum diam quis quam lobortis tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lacinia dapibus metus, sit amet varius dolor euismod eu. Quisque at adipiscing tellus. Aliquam erat volutpat. Quisque commodo tempor fermentum. Cras accumsan rutrum erat nec sodales. Ut malesuada eros vitae elit lacinia eget viverra tortor tempor. Nunc in lorem nec sem varius ultricies eu sit amet nulla.

Cras vestibulum hendrerit mi non dictum. Morbi augue enim, lobortis non rutrum dapibus, adipiscing eu quam. Proin imperdiet velit vitae odio sagittis eleifend. Cras posuere dictum auctor. Donec luctus interdum fringilla. Ut ac nisl eget turpis fermentum tincidunt non non orci. Curabitur faucibus urna eu sapien elementum volutpat. Curabitur tempor, elit eu ultricies faucibus, turpis erat consequat ante, at dictum neque leo sed arcu. Nunc ac turpis at lacus venenatis pellentesque eu et leo. Suspendisse placerat dui vitae nulla imperdiet sollicitudin. Vivamus ornare, ligula bibendum consectetur eleifend, justo orci ornare enim, non condimentum augue lorem ac ante.

Fusce sagittis semper gravida. Duis aliquam euismod volutpat. Aenean porttitor gravida massa vel sagittis. In mauris nulla, lobortis a eleifend at, fermentum at quam. Morbi pulvinar, ante a tincidunt gravida, orci nibh porta mi, eget gravida libero tellus porttitor augue. Maecenas et dolor eget nunc commodo ullamcorper vitae nec libero. Donec sed diam sed augue auctor pretium. Donec lectus eros, pellentesque sit amet pellentesque sed, gravida a odio. Nam tristique tincidunt nisl, et pulvinar dolor adipiscing nec. Cras vehicula quam turpis, fringilla porta lacus. Proin rhoncus dictum quam, ac euismod nisl tristique eleifend. Aliquam auctor pharetra posuere. Curabitur a dui sed ipsum aliquet elementum. Donec risus eros, ornare bibendum suscipit eget, tincidunt quis lacus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam feugiat risus molestie ante lacinia blandit. Proin imperdiet imperdiet convallis.

Duis in arcu in tellus euismod tristique. Morbi blandit, nibh in faucibus egestas, tellus lectus fringilla velit, nec mattis massa nisi in nisl. Nulla mauris metus, sodales id porttitor at, egestas ac mauris. Etiam rhoncus, dui ut convallis adipiscing, turpis elit tincidunt erat, vitae suscipit magna massa sed dolor. Curabitur vulputate nisi eu leo tristique sed rhoncus tellus elementum. Suspendisse commodo ipsum non tellus vulputate pulvinar. Vestibulum ultrices, risus ut ornare pellentesque, nisl est facilisis dolor, non dignissim erat dui vel lacus. Etiam eleifend commodo metus, quis dictum est porttitor sit amet. Integer lorem leo, vulputate suscipit ornare sit amet, posuere vitae nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris eget sem tellus, eu porttitor erat. Vestibulum cursus consectetur magna, ac tempus arcu mollis quis. Integer lobortis tempus turpis, vel vehicula lacus placerat sed. Donec nec arcu mollis lorem ornare lacinia. Duis faucibus pulvinar turpis vitae bibendum. Aenean gravida consectetur commodo. Vestibulum rutrum fringilla suscipit. Nunc a odio nisl. Quisque vel tortor et ipsum tempus ullamcorper id quis risus.

Etiam luctus scelerisque condimentum. Duis dapibus ultricies tortor, at dignissim massa posuere et. Quisque volutpat ultricies justo suscipit convallis. Nulla pulvinar scelerisque posuere. Quisque hendrerit libero tincidunt felis sagittis pellentesque. Vestibulum vitae risus neque, in condimentum mauris. Pellentesque id ultricies nisi. Aliquam elit leo, vestibulum a vestibulum id, hendrerit nec nunc. Donec quis metus orci, eu tempor risus. Curabitur ac massa dolor, in feugiat diam. Ut fringilla, justo ac ultrices feugiat, lorem elit interdum libero, nec viverra justo leo in augue.

Suspendisse eget tortor ac mi bibendum feugiat in a felis. Maecenas sit amet pulvinar quam. Cras mauris lacus, accumsan vitae mattis id, sagittis ac orci. Proin ut est blandit mauris ullamcorper commodo a sed massa. Mauris aliquam scelerisque augue sit amet tristique. Nulla lacinia erat at massa accumsan sed iaculis ipsum tempus. Proin eu turpis quam. Sed sit amet purus nec magna convallis consequat. Nam dignissim mi tristique felis faucibus iaculis. Nunc sapien lacus, porta non aliquam sed, dignissim eget quam. Quisque dictum sem ac erat aliquet sed porta erat tristique. Donec sed ipsum nec nisi aliquet venenatis. Suspendisse tincidunt, ante vitae dignissim viverra, augue sem congue elit, et porttitor mi nunc sed nisi. Nam consectetur nulla quis dolor condimentum in sodales tellus convallis.

Mauris suscipit, metus sit amet euismod elementum, neque erat sodales enim, eu euismod nunc sem adipiscing nisi. Curabitur vel tortor eget urna posuere scelerisque a quis felis. Donec eu nisi enim. Donec condimentum massa sed elit tincidunt lacinia. Donec dignissim risus pretium urna pretium dignissim. Praesent semper pellentesque dignissim. Nulla egestas odio eros, nec pretium dolor. Vivamus quis turpis neque, vel mollis elit. Fusce convallis aliquet eros, id aliquet nisi ultrices interdum. Nulla eleifend blandit leo, eu mollis lectus aliquam sed. Aliquam fermentum lectus vitae sapien varius vel volutpat augue fermentum. Aenean dapibus venenatis erat, at fringilla sem consectetur eget. Pellentesque gravida arcu consectetur lacus pretium nec interdum dui tempor. Sed cursus feugiat mauris vitae dignissim. Donec dapibus neque quis augue semper ultricies. Morbi fringilla massa non nunc bibendum tempor. Cras lacus nibh, cursus vel facilisis a, ornare eu nisi. Ut eget sem urna, non condimentum eros. Sed fermentum lectus sed lacus semper convallis. Mauris condimentum velit sed est congue mollis.

Cras nulla libero, vehicula et tincidunt eget, venenatis et velit. Pellentesque posuere, eros ac scelerisque sodales, nulla nunc commodo augue, vel vestibulum dui lacus porttitor dolor. Nunc ornare vehicula condimentum. Cras rutrum, elit vitae eleifend pharetra, odio turpis imperdiet nisl, sit amet pretium orci nulla sed turpis. Duis tempor, metus ut rhoncus accumsan, libero nibh varius metus, non lobortis nisl eros vitae velit. Praesent in lectus rhoncus est venenatis aliquam vitae eget lacus. Vivamus non orci sed ligula fermentum scelerisque. Donec et consequat erat. Mauris vitae purus nisi. Sed congue convallis orci quis eleifend. Quisque velit dui, tempor quis lacinia vitae, mattis eu felis. Integer urna massa, blandit id porttitor eu, ultricies mollis tellus. Vestibulum a porttitor magna. Morbi vitae elit ante, vulputate congue mauris. Sed nec sollicitudin metus. Nulla justo urna, rutrum nec vestibulum vel, scelerisque at justo. Vivamus nec massa orci, sed vestibulum enim.

Curabitur euismod dolor auctor est ultricies non ornare quam tempus. Morbi porta sapien eu tortor porta eget interdum turpis pretium. Morbi elementum magna non risus sollicitudin vehicula. Cras eros nunc, adipiscing a cursus sit amet, iaculis ut justo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis leo mi, pretium sit amet imperdiet non, pulvinar at nisi. Curabitur ut tortor ut turpis tincidunt cursus vitae sit amet lacus. Suspendisse congue elit vitae metus viverra varius. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis et semper libero. Curabitur consequat, ligula ac pharetra sodales, lacus sem fermentum velit, vitae euismod purus lacus laoreet urna. Etiam placerat luctus pharetra. Phasellus interdum nulla ut erat condimentum hendrerit. Aliquam eget nunc eu diam congue imperdiet id mattis arcu. Duis iaculis nunc sed dolor imperdiet non sagittis purus mattis. Mauris vulputate tellus ac magna pellentesque in fringilla mi fringilla. Phasellus nec magna lacus. Aenean cursus sollicitudin velit blandit condimentum.

Ut mauris augue, bibendum id pulvinar ut, aliquet id felis. Nulla vitae massa eget sem mollis imperdiet. Integer nulla purus, aliquet nec rhoncus ut, pharetra nec nunc. Aliquam sed rhoncus justo. Praesent quis mi enim, a interdum dolor. Etiam vulputate mauris in elit porttitor adipiscing. Donec sagittis fringilla accumsan. Integer et sagittis orci. Nulla adipiscing sapien et dolor feugiat bibendum. Fusce ut facilisis magna. Etiam hendrerit tortor ut ligula pellentesque at ultrices sem sagittis. Vivamus vehicula, risus eget faucibus lacinia, augue nibh sagittis dui, nec pulvinar tellus ipsum dapibus leo. Aliquam erat volutpat. In mollis hendrerit sapien, nec porta elit vehicula sed. Mauris id vehicula nulla. Morbi malesuada nisl sit amet nisl eleifend consequat. Suspendisse in sollicitudin elit.

Sed cursus est eu tellus eleifend a rhoncus neque feugiat. Vestibulum elementum pretium enim, ac fringilla odio euismod quis. Vestibulum non libero vel velit aliquet volutpat lacinia eu est. Aenean vestibulum metus eget neque lacinia in consequat metus accumsan. Etiam tincidunt orci vel felis facilisis et cursus risus egestas. Mauris vitae mi facilisis leo pretium auctor. Duis semper accumsan ipsum, vel tincidunt libero gravida in. Maecenas a nunc quis lacus feugiat porttitor. Pellentesque vel magna sit amet est hendrerit lacinia. Aenean pretium, ante ac imperdiet eleifend, sem leo tincidunt augue, ut porta augue quam quis libero. Mauris et lacus sed leo tincidunt pellentesque ac sit amet ligula. Quisque vehicula mauris ut mauris condimentum id ultrices risus facilisis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec metus nunc, rhoncus ac commodo et, dapibus at quam. Nunc laoreet interdum felis at tincidunt. Suspendisse accumsan massa malesuada neque sagittis sit amet dictum massa porta. Suspendisse volutpat aliquam molestie.

Duis lectus erat, laoreet non lacinia eget, venenatis a mi. Cras aliquam nibh ut elit lacinia mattis. Phasellus eu ultrices augue. Quisque fermentum blandit ornare. Nam venenatis pellentesque nisi, ac faucibus felis euismod sed. Mauris quis tincidunt ligula. Vestibulum eget lectus ipsum, vel euismod velit. Vestibulum lacinia, elit a ultrices interdum, mauris nibh consequat turpis, vitae porta nunc ipsum et lectus. Aliquam vel odio ut sem rutrum congue vel in libero. Duis a quam vitae metus sollicitudin tincidunt lobortis ut felis. Aenean blandit metus eget magna tempor interdum. Nulla ut dapibus orci. Nulla ipsum risus, sodales id dignissim vitae, convallis consectetur orci. Pellentesque eu eros tortor, et dapibus sapien. Mauris dolor massa, tempor id malesuada ac, adipiscing quis dolor.

Etiam sit amet ligula velit, at cursus est. Ut ut posuere eros. Donec porttitor, urna sit amet semper sollicitudin, leo magna tempor augue, sit amet auctor sapien quam a ipsum. Donec eu ipsum ipsum. Fusce lectus sapien, mollis id vestibulum quis, mollis placerat diam. Proin id fringilla velit. Pellentesque velit quam, pharetra et pulvinar vel, vestibulum id tortor. Vivamus malesuada tellus quis libero consectetur lacinia. Aliquam dolor quam, dignissim at volutpat at, facilisis a tortor. Suspendisse potenti. Vivamus lorem massa, egestas molestie viverra et, molestie tincidunt eros. Nunc est libero, dapibus vel condimentum nec, commodo ac nunc. In hac habitasse platea dictumst. Morbi auctor, lectus at ultricies pharetra, urna turpis semper nisi, vel placerat lacus nibh vel elit. Praesent auctor dictum condimentum. Fusce aliquet ipsum ac elit pretium vitae aliquet velit vestibulum. Donec in velit turpis, facilisis ullamcorper turpis.

Donec ac leo purus, vel lobortis mi. Aliquam a sem quam, ut faucibus velit. Nam suscipit nibh nec dui aliquet ullamcorper. Fusce malesuada tortor sed augue vulputate sodales. Sed odio justo, ultrices id vestibulum ac, vestibulum nec velit. Aenean auctor, nisl sit amet vulputate tincidunt, leo elit placerat nisl, id rhoncus erat mi ac eros. Proin sit amet dui dui. Maecenas interdum, tellus nec cursus suscipit, massa magna condimentum felis, et molestie urna sem vel eros. Donec vel felis non nibh pharetra viverra. Integer orci ipsum, tincidunt eget porttitor et, consectetur sit amet ante.

Cras vitae enim diam, mollis egestas nisi. Aenean vel felis mi, id tristique metus. In sit amet pulvinar lacus. Phasellus adipiscing, purus at tincidunt blandit, velit dui elementum nisi, id dapibus libero tellus ac odio. Duis felis erat, lacinia sed tincidunt vel, luctus non quam. Vivamus sagittis orci urna, eget viverra tellus. Quisque sit amet dolor a sapien consequat tempus at ac sem. Proin lacus urna, accumsan adipiscing porttitor vel, laoreet a risus. Donec vehicula venenatis volutpat. Nulla adipiscing, dui vel euismod suscipit, nulla felis porttitor turpis, et euismod purus magna ut diam. Fusce non urna eget massa ornare eleifend. In nec massa quis libero ornare egestas quis vel elit. Cras lorem neque, suscipit id accumsan a, dictum dignissim nulla. Ut tincidunt odio quis mi suscipit feugiat. In id purus sed leo malesuada gravida vitae ut mi. Morbi gravida nunc sed nunc congue eget tincidunt lectus viverra. Integer tincidunt imperdiet orci ac accumsan. Sed eleifend ipsum sed odio ornare tincidunt. Ut dictum, lorem a malesuada semper, mi metus hendrerit neque, non eleifend nisi dolor nec risus.

Phasellus suscipit erat sit amet magna vestibulum congue. Sed at libero dolor, eget posuere mauris. Fusce id odio magna, et vehicula libero. Ut gravida diam eget urna auctor vestibulum. Donec odio tellus, varius ac consequat id, tincidunt et augue. Donec tempor lectus ut nisi elementum vehicula. Vivamus condimentum neque massa, in ultrices lacus. Nulla facilisi. In hac habitasse platea dictumst. Integer ac velit nisi.

Vestibulum condimentum pretium metus quis interdum. Suspendisse potenti. Nulla sodales nisl at massa consectetur et luctus odio ornare. Aenean vel posuere dui. Vivamus ac commodo massa. Donec ullamcorper pretium nulla sed adipiscing. Sed sem eros, sodales sed tincidunt sit amet, placerat ut mi. Maecenas sit amet faucibus odio. Pellentesque semper, turpis a dapibus pharetra, massa nisl pharetra sapien, id porta nisl ipsum ac arcu. Aliquam ac orci a orci condimentum facilisis vel ac magna. Mauris at orci non turpis malesuada laoreet. Integer in purus vel orci fermentum iaculis et eu turpis. Nunc pellentesque, purus nec eleifend aliquam, magna tellus molestie leo, quis condimentum felis eros ut orci. Etiam ligula augue, ornare quis hendrerit non, lobortis vel urna. In bibendum tempus lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Nam suscipit mollis justo, non vehicula enim fermentum ut. Praesent tempus malesuada ante in pulvinar. Nunc id felis tortor. Maecenas congue lectus ac lectus ornare tincidunt. Nullam condimentum, urna a condimentum convallis, libero tortor convallis metus, vestibulum tempus elit risus a felis. Vivamus justo neque, iaculis ut pellentesque eu, tempor ut metus. Curabitur sodales tellus felis. Mauris nec augue metus. Fusce eros risus, porta vel lacinia eleifend, scelerisque ac mauris. Quisque diam metus, adipiscing sit amet lobortis quis, venenatis ut dui. Nulla eu metus nec massa varius condimentum vitae vitae ipsum. Maecenas leo nisi, rutrum tristique dignissim eu, laoreet non arcu. Curabitur odio libero, convallis lacinia blandit vitae, tincidunt in massa. Nulla non nunc felis. Nulla feugiat nunc eu leo molestie sit amet sagittis nibh pellentesque. Nullam pulvinar orci ut nisi pretium imperdiet. Mauris volutpat posuere ante, non euismod lacus accumsan quis.

Aliquam scelerisque nisl et lectus aliquet quis faucibus purus viverra. Duis ultrices elit ligula, non imperdiet orci. Nunc eget libero ac nunc laoreet porta. In eget sem quis ipsum posuere varius sit amet ac lacus. Nam pharetra odio sit amet dolor porta dignissim. Etiam porttitor placerat vulputate. Quisque turpis orci, scelerisque et consequat at, fringilla vitae nisi. Praesent sagittis aliquet porttitor. Suspendisse augue mauris, placerat a malesuada vel, feugiat posuere nisl. Maecenas placerat sagittis odio non sagittis.

Vivamus lectus nisl, consectetur et commodo sit amet, condimentum id ante. Nulla sit amet nisl sit amet eros pulvinar pellentesque. Fusce lacus purus, sollicitudin id ultricies vitae, feugiat id tellus. Aliquam erat volutpat. Proin molestie pellentesque nunc, vitae commodo justo blandit nec. Nullam suscipit pulvinar nisl. Nunc pretium hendrerit tellus, eu elementum nisl sollicitudin in. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla pellentesque urna at leo ornare cursus suscipit metus imperdiet. Duis ante ipsum, tristique a vestibulum ut, sodales eget ligula. Phasellus lectus nunc, sollicitudin vel imperdiet eleifend, venenatis in ipsum. Donec non tellus odio. Aenean sodales, tellus eu posuere semper, metus orci ornare magna, id posuere dolor ipsum a orci. Nulla interdum pellentesque eros, sed dignissim est interdum sed. Nullam id sapien non diam congue malesuada. Sed in sapien libero.

Quisque faucibus porta semper. Suspendisse pellentesque purus sollicitudin est malesuada rutrum. Suspendisse placerat tristique lobortis. Aliquam eu tortor eget dolor accumsan viverra. Donec tempor quam eget elit rhoncus quis ultricies risus egestas. Nullam pharetra leo quis lectus sagittis vitae mollis ipsum consequat. Suspendisse potenti. Nullam fermentum, metus ut hendrerit hendrerit, tellus ipsum pharetra est, vel egestas tellus nisi eget nisi. Nulla facilisi. Fusce justo dui, gravida eget interdum vitae, congue sed neque. Maecenas massa nunc, varius sed adipiscing non, pellentesque sagittis leo. Vivamus semper sem quis augue mattis placerat.

Maecenas odio magna, condimentum vitae aliquam et, accumsan et odio. Etiam sed ligula non erat venenatis accumsan ornare in leo. Sed ac mauris ipsum, ut facilisis quam. Quisque luctus elit orci, vitae commodo leo. Phasellus luctus tincidunt cursus. Aliquam iaculis venenatis est vitae facilisis. Aliquam adipiscing vehicula arcu in lobortis. Nulla gravida nibh et sapien fringilla auctor. Proin dolor nisi, tincidunt at cursus eget, malesuada vel lorem. In id magna augue, sed dictum tortor. Proin placerat pharetra tempor. Cras et quam eget augue molestie vulputate nec eget urna. Pellentesque consectetur nulla non velit fringilla ac ultricies mauris imperdiet. In hac habitasse platea dictumst.

Nunc nec blandit tortor. Aliquam bibendum diam in urna egestas ut ultricies erat fermentum. Nulla purus metus, luctus sit amet dictum ac, rutrum sit amet ipsum. Sed quam nulla, placerat sit amet pretium sagittis, cursus fringilla metus. Maecenas vulputate, massa eget tempor luctus, neque erat pellentesque neque, ut aliquam libero mauris cursus sem. Cras non lacus nec augue lobortis hendrerit in a ipsum. Sed volutpat tincidunt massa, vitae vehicula neque auctor eu. Etiam ornare nisi sit amet ligula tincidunt et laoreet nunc aliquet. Morbi lacus metus, dignissim eget porta quis, pulvinar ac neque. Fusce sit amet erat ac nisl malesuada volutpat. In lobortis dolor ac nulla suscipit quis laoreet mi ornare. Cras scelerisque ultrices lacus, a euismod diam facilisis et. Vestibulum feugiat tincidunt diam non aliquam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi nec nunc sit amet tellus dapibus convallis eu eu eros. Donec sed tempus augue.

In cursus lectus vel sapien eleifend nec consectetur magna tempus. Mauris tempor accumsan aliquam. Nulla tempus luctus justo a molestie. Cras bibendum vulputate sagittis. Integer commodo pretium dolor, quis viverra elit posuere vel. Etiam justo felis, volutpat quis sagittis eget, luctus eu eros. Duis faucibus porta libero eu rutrum. Etiam cursus magna quis tellus tristique lobortis. Maecenas id turpis tortor, non tincidunt ligula. Phasellus id risus non velit commodo condimentum. Maecenas eu metus justo.

In et sagittis erat. Mauris sodales, dolor id porta consectetur, purus massa vulputate ante, a eleifend nisi dui non purus. Curabitur enim elit, eleifend a tempor at, pellentesque ac velit. Fusce tellus tellus, eleifend vitae rhoncus ac, pretium et mauris. Quisque ac augue id massa dapibus egestas. Etiam faucibus, sapien non eleifend aliquet, dolor libero ornare augue, eu dictum leo leo eu orci. Aliquam eget nibh eget urna luctus eleifend. Sed ac eros at erat facilisis suscipit. Nullam eu interdum magna. Aliquam tincidunt tristique tellus non bibendum. Aenean fermentum, risus sed pretium varius, orci ipsum eleifend nisi, id semper massa orci in nulla. Phasellus iaculis, libero id facilisis luctus, est magna dictum est, vitae condimentum lacus ante at augue.

Praesent hendrerit tellus quis augue ullamcorper vel adipiscing massa porttitor. Nunc vitae odio lacus. Mauris tempus lorem eu ipsum aliquet luctus. Etiam convallis, arcu in tempus pellentesque, est orci volutpat sapien, id fermentum tellus nisl ut mauris. Pellentesque a sapien arcu. Donec ut sagittis elit. Mauris rhoncus consequat eleifend. Nulla mi neque, fermentum et congue vel, varius vitae arcu. Morbi pulvinar accumsan nisl quis porta. Ut risus diam, ornare ac ultricies vel, viverra ac justo. Vivamus in justo ante. Nullam dictum lacus tempus dolor faucibus commodo. Nam consectetur nibh felis. Mauris luctus lacinia malesuada. Sed elementum iaculis est, eu ultrices libero iaculis ac. Suspendisse quis augue et mauris convallis suscipit. Suspendisse potenti. Nulla at metus facilisis enim porta blandit bibendum sit amet orci. Nunc eu dictum odio. Aliquam erat volutpat.

Aenean sit amet magna sit amet lectus tincidunt porttitor et eget ante. Nam bibendum, nulla ac pharetra ullamcorper, nisl odio ullamcorper tellus, eu facilisis felis arcu sit amet tortor. Vestibulum id tortor dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent eget dui odio. Donec scelerisque egestas dui, eget varius sem accumsan quis. Fusce at porttitor lorem. Donec dapibus nibh in arcu aliquam fermentum et sed diam. Mauris dictum, odio in ultricies sollicitudin, massa urna rhoncus mauris, ac luctus nisl massa in turpis. Nam in enim arcu. Morbi eu ipsum et tellus pretium porttitor. Pellentesque quis sapien at lacus aliquam hendrerit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque risus nulla, feugiat sit amet lacinia ut, malesuada sed dui. Aliquam vehicula sapien eget enim posuere in faucibus dolor egestas. Sed dictum quam eget enim molestie ac ullamcorper tellus varius. Pellentesque blandit, dui ut dictum ullamcorper, neque mauris egestas massa, in volutpat mi eros vitae leo. Duis in neque id nisl ornare semper eget non nisi.

In hac habitasse platea dictumst. Vivamus pulvinar metus eu ipsum sodales sed ultrices metus tristique. Donec interdum, enim in adipiscing mollis, nisi sem pretium lectus, ac ornare urna nulla eu mi. Fusce eu nulla et magna volutpat adipiscing at nec elit. Donec ornare dui eget ipsum lobortis molestie. Integer nisl erat, sollicitudin rutrum lobortis at, pulvinar quis mi. Vivamus fermentum aliquam faucibus. Ut iaculis pulvinar massa, in suscipit neque facilisis nec. Sed nec risus ligula, ultricies tempus neque. Sed rutrum gravida justo, vel dignissim lectus rutrum sit amet. Ut pretium consectetur leo, quis gravida nunc mattis nec. Quisque id elit nisi, vel suscipit massa. Aenean elementum suscipit eros quis iaculis. In hac habitasse platea dictumst. Vivamus rhoncus risus ac lectus adipiscing viverra vitae eget mi. Morbi volutpat, libero at aliquet imperdiet, metus turpis aliquet felis, eget sodales tortor dui sit amet justo. Cras tincidunt, tellus ac posuere iaculis, nisi dui euismod lectus, dignissim aliquam dolor dui id dolor. Cras eu pharetra mi.

Morbi ornare rhoncus turpis eu pulvinar. Vestibulum condimentum rhoncus metus nec pellentesque. Fusce vestibulum, arcu eget volutpat dapibus, massa lorem tincidunt elit, a condimentum est nisi vel diam. Mauris hendrerit imperdiet est et ullamcorper. Aenean interdum aliquet adipiscing. Curabitur vulputate, neque ac malesuada tincidunt, mauris tortor ultrices tellus, id sollicitudin ante leo ac diam. Proin vitae varius erat. Sed ac ipsum et massa ullamcorper sodales. In eu luctus augue. Proin venenatis gravida ullamcorper. Vestibulum a ipsum adipiscing justo vehicula porta. Donec sed neque et est imperdiet vestibulum.

Quisque fermentum porta lacus vitae pretium. Sed ultricies lacus ligula, id semper lorem. Maecenas in mi ut est vehicula vulputate ut a sapien. Cras nec consectetur nunc. Mauris id justo tortor, at venenatis arcu. Etiam scelerisque lorem orci, ac condimentum erat. In hac habitasse platea dictumst. Duis et eleifend dolor. Sed ac velit id dolor blandit vestibulum sed vitae sapien. Maecenas eu erat quis metus ultricies egestas. Donec eget tellus varius dui dapibus pharetra at id metus. Etiam auctor nulla in ligula fermentum ornare. Vestibulum a ultricies risus. Vivamus in velit sit amet arcu pellentesque blandit quis vel ligula. Donec lectus metus, adipiscing ac rhoncus vitae, ornare vel dolor. Aenean eget est nec magna dignissim semper sed ac nibh. Nunc cursus, urna nec ultricies feugiat, tellus ligula dapibus massa, non mollis enim orci quis neque. Pellentesque ut nisi lectus. Mauris at lorem tortor, et gravida ipsum.

Praesent a lorem purus. Nunc felis elit, blandit quis sodales in, accumsan ut dui. Pellentesque sed erat quis nisi eleifend sodales et quis eros. Aliquam rhoncus justo sit amet mi porta a varius ipsum aliquam. Nam quis semper nisi. In eros elit, adipiscing fermentum aliquam id, auctor at justo. Nullam scelerisque, ipsum at dapibus lacinia, erat metus fermentum lorem, et porta ligula nisi at sapien. Proin et eros nisl. Quisque consequat malesuada odio non vulputate. Suspendisse a dolor ante, sed cursus urna. Ut porta ligula a ante elementum et ullamcorper magna feugiat. Suspendisse eros nisi, porta sit amet hendrerit vitae, eleifend vitae odio. Vivamus at lorem nec sapien auctor interdum nec sit amet metus. Curabitur at mauris tortor, vel porttitor erat. In sed mi elit. Pellentesque viverra justo a neque faucibus et pellentesque nisl consectetur. Donec volutpat, orci at vulputate hendrerit, lorem ante gravida augue, vitae fermentum massa urna sit amet magna. Nunc interdum, lectus non scelerisque facilisis, nulla tellus vulputate mi, sit amet luctus enim nisi nec tortor. Maecenas ultrices volutpat interdum.

In ornare gravida ligula sed commodo. Vestibulum pulvinar sodales metus, a sollicitudin massa lobortis sit amet. Ut a ultrices nunc. Nulla ut nibh enim, vehicula blandit lorem. Aliquam velit nisi, pretium a suscipit vitae, feugiat quis metus. Ut quis dui lorem. Ut rutrum dapibus enim eu luctus. Aenean justo turpis, dignissim eu pellentesque aliquam, vehicula non ipsum. Phasellus sit amet tellus massa. Vestibulum sit amet nunc sapien, eget egestas ipsum. Pellentesque a dui eu urna aliquet ornare. Phasellus augue urna, hendrerit id viverra et, porta in tortor. Vestibulum erat dolor, rutrum sed iaculis id, aliquet quis nibh. Donec porta, velit in viverra suscipit, nulla mauris adipiscing lectus, sit amet euismod erat orci et neque. Proin feugiat ultrices nulla in cursus. Nullam ut sollicitudin nisl.

Donec nec risus sit amet augue rutrum malesuada et id ante. Aliquam quis nulla sapien, ac eleifend leo. Curabitur placerat suscipit turpis quis laoreet. Proin at tellus tincidunt nibh ornare gravida vel ut dolor. Vivamus cursus orci nisi. Cras adipiscing ligula aliquet nisl luctus consectetur. Nam urna urna, bibendum quis tincidunt pellentesque, commodo sed ipsum. Aenean orci sem, viverra sit amet gravida ac, consectetur eget lorem. Integer orci nunc, eleifend in ultrices ornare, mollis non ante. Sed faucibus sagittis elit, vitae tincidunt ligula rutrum quis. Donec rhoncus elementum fermentum. Phasellus ut tellus arcu, vel vehicula tellus. Suspendisse pulvinar ultricies turpis, id convallis nisi blandit vitae. Praesent egestas porta elit volutpat dapibus. Morbi tempus, elit sit amet viverra feugiat, velit justo bibendum ipsum, ultrices blandit mi metus at nisl. Aliquam rutrum nibh eget sapien pellentesque lobortis.

Fusce consectetur quam ac tellus malesuada sagittis. Vestibulum eu dolor at elit ullamcorper consequat eget eget lectus. Vestibulum aliquet posuere pellentesque. Proin sem arcu, interdum id eleifend at, venenatis quis purus. Nulla lorem est, ullamcorper ut accumsan sed, iaculis sit amet quam. Morbi commodo porta elementum. Quisque rhoncus scelerisque quam ut tristique. Proin mattis tellus sed ante blandit et scelerisque dui porta. Sed consectetur pulvinar nunc, non fermentum urna feugiat nec. Nunc vel metus vitae dolor posuere condimentum. Vivamus dui mauris, venenatis sed euismod vitae, ullamcorper sollicitudin neque. Mauris tincidunt aliquam condimentum. 

	<script type="text/javascript" src="Assets/Scripts/Libraries.php"></script>
</body>
</html>
